# Site settings
main_color: "yellow"
# blue red pink yellow
title: "Manhunt - #1 Gay Dating App"
keywords: "dating chat meet date hookup sexting social flirting stranger casualx flirt gay manhunt tinder sex"
app_name: "Manhunt - #1 Gay Dating App"
app_domain: "manhunt.datingapp.me"
support_email_address: "manhunt-support@datingapp.me"
appstore_url: "https://itunes.apple.com/us/app/id1463028292"
#url: "http://127.0.0.1:4000/"
url: "https://manhunt.datingapp.me"
# Build settings
markdown: kramdown
