# Site settings
main_color: "yellow"
# blue red pink yellow
title: "Manhunt - #1 Gay Dating App"
description: "Manhunt - #1 Gay Dating App is a new leading gay dating app, helping gay singles find their perfect match. Manhunt makes it fun and easy for gay, bi and curious guys to connect with each other. Find cool guys and keep in touch, yours “Mr. Nearby” may appear! Then watch gay from all over the world start to message and flirt with you. Manhunt just matches you with other real people, so you can make elite friends and chat with them. With our app, you do not need to waste time. Our users do not want to wait, they like to LIVE IT UP! Find love, go on a date and find that special someone"
keywords: "dating chat meet date hookup sexting social flirting stranger casualx flirt gay manhunt tinder sex"
app_name: "Manhunt - #1 Gay Dating App"
app_domain: "manhunt.datingapp.me"
support_email_address: "manhunt-support@datingapp.me"
appstore_url: "https://itunes.apple.com/us/app/id1463028292"
#url: "http://127.0.0.1:4000/"
url: "https://manhunt.datingapp.me"
# Build settings
markdown: kramdown
