# Site settings
main_color: "red"
# blue red pink yellow
title: "_APPNAME_"
app_name: "_APPNAME_"
app_domain: "_APPDOMAIN_"
support_email_address: "support@_APPDOMAIN_"
appstore_url: "https://itunes.apple.com/us/app/id1410616319"
# url: "http://localhost:4000/"
url: "https://callrecorder.io/"
# Build settings
markdown: kramdown
