# Site settings
main_color: "yellow"
# blue red pink yellow
title: "Manhunt Dating App"
app_name: "Manhunt Dating App"
app_domain: "manhunt.datingapp.me"
support_email_address: "support@_APPDOMAIN_"
appstore_url: "https://itunes.apple.com/us/app/id1410616319"
url: "https://manhunt.datingapp.me/"
# Build settings
markdown: kramdown
