# Site settings
main_color: "yellow"
# blue red pink yellow
title: "Call Recorder Rec Phone Call"
app_name: "Call Recorder Rec Phone Call"
app_domain: "callrecorder.us"
support_email_address: "support@callrecorder.us"
appstore_url: "https://itunes.apple.com/us/app/id1410616319"
#url: "http://localhost:4000/"
url: "https://callrecorder.us/"
# Build settings
markdown: kramdown
